// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jysibgzxzgjtvwjwxigb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5c2liZ3p4emdqdHZ3and4aWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODA2NjcsImV4cCI6MjA1ODc1NjY2N30._V7kI03qrIN2Wctxp3oVYy-KzEv9ygixT55dRgTz2TE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);